services:
  - type: web
    plan: free
    name: django_1
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_1.asgi:application -k uvicorn.workers.UvicornWorker"